---
version: '3'
services:
  mongo:
    image: mongo
    container_name: momo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

